name: CI
on:
  push:
    # Pattern matched against refs/tags
    tags:        
      - '*'
jobs:
  build:
    name: Build & Publish Latest
    runs-on: ubuntu-latest
    env:
      NPM_TOKEN:  ${{ secrets.NPM_AUTH_TOKEN }}  
    steps:
      - uses: actions/checkout@v2.0.0
      - run: |
          echo "//registry.yarnpkg.com/:_authToken=$NPM_TOKEN" >>~/.npmrc
          yarn install
          yarn build
          yarn publish --tag latest --new-version $(cat package.json | jq -r .version) --non-interactive --no-git-tag-version
